name: Run Scripts Every 5 Minutes

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:  # This enables manual triggering

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Data Producer
      env:
        RABBITMQ_CREDENTIAL: ${{ secrets.RABBITMQCREDENTIAL }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: python data_producer.py

    - name: Run Publisher
      env:
        RABBITMQ_CREDENTIAL: ${{ secrets.RABBITMQCREDENTIAL }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: python publisher.py

    - name: Run Consumer
      env:
        RABBITMQ_CREDENTIAL: ${{ secrets.RABBITMQCREDENTIAL }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: python consumer.py
