jobs:
  producer:
    name: Producer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run producer.py
-      run: |
-        timeout 60s python producer.py
+      run: |
+        timeout 60s python producer.py || true

  consumer:
    name: Consumer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run consumer.py
-      run: |
-        timeout 60s python consumer.py
+      run: |
+        timeout 60s python consumer.py || true