name: Run Scripts

on:
  push:
  workflow_dispatch:  # This enables manual triggering

jobs:
  run-publisher:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Publisher
      env:
        RABBITMQCREDENTIAL: ${{ secrets.RABBITMQCREDENTIAL }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: python producer.py

  run-consumer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Consumer
      env:
        RABBITMQCREDENTIAL: ${{ secrets.RABBITMQCREDENTIAL }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: python consumer.py
