name: Run RabbitMQ Job Daily 2

on:
  schedule:
    - cron: '6 14 * * *'  # Runs at 02:00 UTC daily
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "RABBITMQCREDENTIAL=${{ secrets.RABBITMQCREDENTIAL }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env

      - name: Run app.py
        run: python app.py